theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    header: "/assets/images/logo-icon-white.svg"
    footer: "/assets/images/logo-white.svg"
  breadcrumb:
    position: after-hero
